### ISSUE TITLE
manifest.json

### ISSUE THREAD

**Issue by dan335** [Gamevy/pixi-packer#32]
Is cache.json in ~/.pixi-packer-tmp the file needed by pixi-packer-parser?

If so why is it placed in the tmp directory?  Seems like it should go in the output directory.

**Comment by dan335** [comment]
I found that cache.json is missing the meta key so it must not be the same.  Can't find the json file to use with pixi-packer-parser.

**Comment by dan335** [comment]
I got it working.  If the variations array is empty in images.js then the manifest isn't created and there's no error.

**Comment by marekventur** [comment]
The cache.json is only there for cache reasons, it never needs to be (and never should be) sent to the client. All that will happen if a key is missing or the whole file is removed is that the next processing will take longer.
